apiVersion: v2
name: eduide-shared-cache
description: A Gradle Build Cache server with Redis backend for EduIDE deployments in Kubernetes

type: application

# Bump this version on every release — also used as the Docker image tag
version: 0.5.0

dependencies:
  - name: reposilite
    version: "1.3.25"
    repository: "https://helm.reposilite.com/"
    condition: reposilite.enabled
