{{- if and .Values.enabled .Values.auth.enabled }}
# Read-only cache credentials (for EduIDE / students)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-reader
  labels:
    role: reader
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.auth.reader.username | b64enc | quote }}
  password: {{ .Values.auth.reader.password | b64enc | quote }}
---
# Read-write cache credentials (for CI/CD, admin, cache pre-warming)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-writer
  labels:
    role: writer
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.auth.writer.username | b64enc | quote }}
  password: {{ .Values.auth.writer.password | b64enc | quote }}
{{- end }}
