{{- if .Values.reposilite.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-reposilite-secrets
  labels:
    {{- include "eduide-shared-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-cache
type: Opaque
data:
  adminToken: {{ printf "admin:%s" .Values.reposilite.adminToken | b64enc | quote }}
  prometheusUsername: {{ .Values.reposilite.prometheus.username | b64enc | quote }}
  prometheusPassword: {{ .Values.reposilite.prometheus.password | b64enc | quote }}
{{- end }}
