{{- if .Values.reposilite.enabled }}
{{- $secretName := printf "%s-reposilite-secrets" .Chart.Name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "eduide-shared-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-cache
type: Opaque
data:
  adminToken: {{ printf "admin:%s" .Values.reposilite.adminToken | b64enc | quote }}
  {{- if $existingSecret }}
  prometheusUsername: {{ index $existingSecret.data "prometheusUsername" }}
  prometheusPassword: {{ index $existingSecret.data "prometheusPassword" }}
  {{- else }}
  prometheusUsername: {{ "prometheus" | b64enc | quote }}
  prometheusPassword: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
