{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache
  labels:
    {{- include "theia-shared-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "theia-shared-cache.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache-server
{{- end }}
